### PR TITLE
Fixed presentation documents not being disposed properly

### LINKED ISSUE #3: The output PowerPoint cannot always be opened without closing the script that produced it first
#### Description:
There must be cases where the output file is not released properly.. to be investigated. 

See comment from @FraserGreenroyd for discussion: https://github.com/BHoM/PowerPoint_Toolkit/pull/2#pullrequestreview-1335921111

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #3 

`PresentationDocument.Clone()` creates a clone of the document, which was not being disposed, and caused the document to be locked if a script was not closed. This has been fixed.
General handling of streams has been made more robust, with a `using` statement instead of a try/catch.

Disposal should only need to be done when saving to a file with output file settings: if the output file stream is disposed it would not be usable. 

### Test files

[PowerPoint_Toolkit-#3.zip](https://github.com/user-attachments/files/16174025/PowerPoint_Toolkit-.3.zip)
Unzip and run the grasshopper script, with TemplateDocument.pptx file in the same directory. Then try to open the output file while the grasshopper file is still open.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Review by Felix-Mallinder — DISMISSED** [review]
Reviewed changes which allow for successful opening of outputted PowerPoint document, whilst still running grasshopper script. Works well and as expected.

File: PowerPoint_Adapter/AdapterActions/Push.cs [hunk 1]
```diff
@@ -55,40 +55,12 @@ public override List<object> Push(IEnumerable<object> objects, string tag = "",
             if (pushType == PushType.AdapterDefault)
                 pushType = PushType.UpdateOnly;
 
-
-            MemoryStream memoryStream = null;
-            PresentationDocument presentationDoc = null;
-            try
+            // Open the presentation document
+            using (PresentationDocument presentationDoc = OpenTemplateDocument())
```
Comment (adecler) [inline PowerPoint_Adapter/AdapterActions/Push.cs]: This is replacing a try-finally that was making sure both the presentation document and the memory stream where disposed correctly. 
I am fine with this change as long as you can confirm that the disposal of the presentation document is also disposing of the memory stream. 
This is not explicitly stated in the documentation: https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.packaging.openxmlpackage.dispose?view=openxml-3.0.1#documentformat-openxml-packaging-openxmlpackage-dispose

File: PowerPoint_Adapter/AdapterActions/Push.cs [hunk 2]
```diff
@@ -119,67 +91,72 @@ public override List<object> Push(IEnumerable<object> objects, string tag = "",
...
+            try
+            {
+                return PresentationDocument.Open(memoryStream, true);
+            }
+            catch (Exception ex)
             {
-                BH.Engine.Base.Compute.RecordError($"There is no presentation with the file path {filePath}");
+                BH.Engine.Base.Compute.RecordError(ex, "An error occurred while trying to open the template presentation.");
                 return null;
             }
```
Comment (adecler) [inline PowerPoint_Adapter/AdapterActions/Push.cs]: - Creation of the stream directly in line 117 instead of initializing it as null means that an empty memory stream will be replaced in line 120 without being disposed
 - The catch doesn't dispose of the memory stream. This is only fine if the presentation has already registered the stream in its resources  before the exception is thrown and if the presentation disposes of the stream when being disposed. Can we be 100% sure those two ifs are always true ?

File: PowerPoint_Adapter/AdapterActions/Push.cs [hunk 3]
```diff
@@ -119,67 +91,72 @@ public override List<object> Push(IEnumerable<object> objects, string tag = "",
...
 
         /***************************************************/
         /**** Private Methods                           ****/
         /***************************************************/
 
-        private MemoryStream OpenTemplateFile(string filePath)
+        private PresentationDocument OpenTemplateDocument()
         {
-            // Make sure the file exists
-            if (!File.Exists(filePath))
```
Comment (adecler) [inline PowerPoint_Adapter/AdapterActions/Push.cs]: Why removing this ?

**Review by adecler — CHANGES_REQUESTED** [review]
The disposal of the cloned presentation fixes the problem.
However, this PR also introduces a series of additional changes that have the potential to create new issues (see comments)

File: PowerPoint_Adapter/AdapterActions/Push.cs (hunk 3 above)
Comment (Tom-Kingstone) [reply PowerPoint_Adapter/AdapterActions/Push.cs]: The check for the file not existing is covered by `OpenTemplateFile(string filePath)` starting line 142. The error message produced if the file does not exist is adequate for a user to understand what happened.

Comment (adecler) [reply PowerPoint_Adapter/AdapterActions/Push.cs]: The removed check was inside the `OpenTemplateFile` method so not sure what you mean: 
image

It is always better to explicitly check for invalid input than to rely on try-catches. I also don't understand why you are changing perfectly valid code that is outside of the scope of the issue addressed in this PR

File: PowerPoint_Adapter/AdapterActions/Push.cs (hunk 1 above)
Comment (Tom-Kingstone) [reply PowerPoint_Adapter/AdapterActions/Push.cs]: I looked through, and there is an overload for Dispose that also disposes unmanaged resources using a bool. This is called by the un-overloaded Dispose() method, which disposes unmanaged resources. I am however unconfident in the disposal of the memory stream, so I will revert this.

File: PowerPoint_Adapter/AdapterActions/Push.cs [hunk 4]
```diff
@@ -83,10 +82,9 @@ public override List<object> Push(IEnumerable<object> objects, string tag = "",
                 {
                     presentationDoc = PresentationDocument.Open(memoryStream, true);
                 }
-                catch (Exception e)
+                catch (Exception ex)
                 {
-                    memoryStream.Close();
-                    BH.Engine.Base.Compute.RecordError("Could not open the file: " + e.Message);
+                    BH.Engine.Base.Compute.RecordError(ex, "An error occurred while opening the presentation.");
```
Comment (adecler) [inline PowerPoint_Adapter/AdapterActions/Push.cs]: Can we use the word `template` instead of `presentation` to make it clearer to the user what file this error is related to ?
Can we also keep the exception's message in the error message? This can help understand where the error is coming from when in the UI.

File: PowerPoint_Adapter/AdapterActions/Push.cs [hunk 5]
```diff
@@ -119,34 +117,25 @@ public override List<object> Push(IEnumerable<object> objects, string tag = "",
...
                         presentationDoc.Clone(m_OutputStream);
                         m_OutputStream.Position = 0;
                     }
-
                 }
-                catch (Exception e)
+                catch (Exception ex)
                 {
-                    BH.Engine.Base.Compute.RecordError("Could not save the changes: " + e.Message);
+                    BH.Engine.Base.Compute.RecordError(ex, "An error occurred when trying to save the presentation.");
```
Comment (adecler) [inline PowerPoint_Adapter/AdapterActions/Push.cs:129]: Can we keep the exception's message in the error message? 
This can help understand where the error is coming from when in the UI.

File: PowerPoint_Adapter/AdapterActions/Push.cs [hunk 6]
```diff
@@ -156,30 +145,29 @@ public override List<object> Push(IEnumerable<object> objects, string tag = "",
...
-                fileStream.CopyTo(memoryStream);
-                fileStream.Close();
+                using (FileStream fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
+                    fileStream.CopyTo(memoryStream);
             }
-            catch (Exception e)
+            catch (Exception ex)
             {
-                BH.Engine.Base.Compute.RecordError("Could not open the file: " + e.Message);
+                BH.Engine.Base.Compute.RecordError(ex, "An error occurred when trying to open the template file.");
```
Comment (adecler) [inline PowerPoint_Adapter/AdapterActions/Push.cs]: Same thing here, can we keep the exception's message in the error message?

**Review by adecler — CHANGES_REQUESTED** [review]
The new commit addresses the comments from my previous review.
There are, however, a few minor corrections I would like to see on the error recording before approving the PR.

File: PowerPoint_Adapter/AdapterActions/Push.cs (hunk 4 above)
Comment (Tom-Kingstone) [reply PowerPoint_Adapter/AdapterActions/Push.cs]: The `RecordError` method includes the exception message in the error message, as below. Though I will make the message itself clearer.
image

Comment (adecler) [reply PowerPoint_Adapter/AdapterActions/Push.cs]: Ah, right! I had forgotten about that feature.

**Review by adecler — APPROVED** [review]
The requested changes have been addressed. Happy to approve.

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge
